# Generated by Django 5.2.6 on 2025-09-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IFRA_NCS_Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=1, verbose_name='IFRA NCS code - letter part')),
                ('description', models.CharField(blank=True, default='', max_length=50, verbose_name='CAS Registry Number')),
                ('example', models.CharField(blank=True, default='', max_length=255, verbose_name='xxx')),
                ('comment', models.CharField(blank=True, default='', max_length=255, verbose_name='xxx')),
            ],
        ),
        migrations.CreateModel(
            name='IFRA_NCS_Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=8, verbose_name='IFRA NCS code - number part')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='CAS Registry Number')),
                ('example', models.CharField(blank=True, default='', max_length=255, verbose_name='xxx')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CAS', models.CharField(blank=True, default='', max_length=12, verbose_name='CAS Registry number')),
                ('name', models.CharField(max_length=500, verbose_name='Product name in invoice')),
                ('is_syntetic', models.BooleanField(default=True)),
                ('IFRA_NCS_category', models.CharField(blank=True, default='', max_length=12, verbose_name='IFRA naturals (NCS) category')),
                ('synonyms', models.CharField(max_length=500, verbose_name='Product name in invoice')),
            ],
        ),
    ]
