# Generated by Django 5.2.6 on 2025-09-15 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=40)),
                ('CAS', models.CharField(max_length=12)),
                ('product_name', models.CharField(max_length=100)),
                ('dilution', models.PositiveSmallIntegerField()),
                ('quantity', models.DecimalField(decimal_places=1, max_digits=4)),
                ('quantity_unit', models.CharField(choices=[('g', 'Gram'), ('ml', 'Milliliter')], max_length=2)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('GBP', 'GBP'), ('EUR', 'EUR')], max_length=3)),
                ('comments', models.CharField(max_length=200)),
                ('supplier', models.CharField(max_length=100)),
                ('delivery_date', models.DateTimeField(verbose_name='delivery date')),
            ],
        ),
    ]
