# Generated by Django 5.2.6 on 2025-09-16 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=200)),
                ('purchase_date', models.DateTimeField(verbose_name='delivery date')),
            ],
        ),
        migrations.AddField(
            model_name='invoiceitems',
            name='invoice_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='inventory.invoice'),
            preserve_default=False,
        ),
    ]
