# Generated by Django 5.2.6 on 2025-09-16 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_invoice_invoiceitems_invoice_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvoiceItems',
            new_name='InvoiceItem',
        ),
    ]
