# Generated by Django 5.2.6 on 2025-09-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_invoiceitems_invoiceitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='item_code',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='supplier',
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='code',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Product code in invoice'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='manufacturer',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Manufacturer of the product'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Product name in invoice'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='solvent',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Solvent used for diluting'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='test_by_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiration or re-testing date for product'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='CAS',
            field=models.CharField(blank=True, default='', max_length=12, verbose_name='CAS Registry Number'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='comments',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Comments for the item in invoice'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('GBP', 'GBP'), ('EUR', 'EUR')], max_length=3, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='dilution',
            field=models.PositiveSmallIntegerField(blank=True, default='100', verbose_name='Dilution in percentage (1-100)'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total price of item'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='quantity',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Quantity - a number in a given unit'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='quantity_unit',
            field=models.CharField(choices=[('g', 'Gram'), ('ml', 'Milliliter')], max_length=2, verbose_name='Unit of measuring quantity (mg, ml, ...)'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price for a unit of item '),
        ),
    ]
