# Generated by Django 5.2.6 on 2025-09-18 15:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_invoiceitem_delivery_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='purchase_date',
        ),
        migrations.AddField(
            model_name='invoice',
            name='delivery_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='delivery date'),
            preserve_default=False,
        ),
    ]
