# Generated by Django 5.2.6 on 2025-09-18 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_invoice_purchase_date_invoice_delivery_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Invoice',
            new_name='Order',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=40, verbose_name='Product code in invoice')),
                ('CAS', models.CharField(blank=True, default='', max_length=12, verbose_name='CAS Registry Number')),
                ('name', models.CharField(max_length=100, verbose_name='Product name in invoice')),
                ('manufacturer', models.CharField(blank=True, default='', max_length=100, verbose_name='Manufacturer of the product')),
                ('dilution', models.PositiveSmallIntegerField(blank=True, default='100', verbose_name='Dilution in percentage (1-100)')),
                ('solvent', models.CharField(blank=True, default='', max_length=100, verbose_name='Solvent used for diluting')),
                ('quantity', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Quantity - a number in a given unit')),
                ('quantity_unit', models.CharField(choices=[('g', 'Gram'), ('ml', 'Milliliter')], max_length=2, verbose_name='Unit of measuring quantity (mg, ml, ...)')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price for a unit of item ')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total price of item')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('GBP', 'GBP'), ('EUR', 'EUR')], max_length=3, verbose_name='Currency')),
                ('comments', models.CharField(blank=True, default='', max_length=200, verbose_name='Comments for the item in invoice')),
                ('test_by_date', models.DateTimeField(blank=True, null=True, verbose_name='Expiration or re-testing date for product')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.order')),
            ],
        ),
        migrations.DeleteModel(
            name='InvoiceItem',
        ),
    ]
