# Generated by Django 5.2.6 on 2025-09-18 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_rename_invoice_order_product_delete_invoiceitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='order_id',
            new_name='order',
        ),
    ]
