# Generated by Django 5.2.6 on 2025-09-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_rename_order_id_product_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(null=True, verbose_name='delivery date'),
        ),
    ]
