# Generated by Django 5.2.6 on 2025-09-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_order_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='comments',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Comments for the item in invoice'),
        ),
    ]
